on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Environment variables available to all jobs and steps in this workflow
env:
  ANGULAR_IMAGE_NAME: social-login-app-client
  ANGULAR_CONTAINER_NAME: social-login-app-client
  ANGULAR_DEPLOYMENT_NAME: social-login-app-client
  SPRING_BOOT_IMAGE_NAME: social-login-app-server
  SPRING_BOOT_CONTAINER_NAME: social-login-app-server
  SPRING_BOOT_DEPLOYMENT_NAME: social-login-app-server
jobs:

  build:
    name: Build, push, and deploy
    runs-on: self-hosted
    steps:

    - name: Checkout main
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Provide permission to run mvnw
      run: chmod +x ./spring-boot-oauth2-social-login/mvnw
